/**
 * data/{h,spq,cpq}.data -> src/trie-data.generated.ts (gzip + base64)
 * Only needed by anyone who wants the embedded browser fallback; Node reads
 * data/ directly.
 */
import { readFileSync, writeFileSync, statSync } from "node:fs";
import { gzipSync } from "node:zlib";

const names = ["h", "spq", "cpq"];
const body = names
  .map(n => `export const ${n.toUpperCase()}_GZ_B64 = "${gzipSync(readFileSync(`data/${n}.data`), { level: 9 }).toString("base64")}";`)
  .join("\n");

writeFileSync(
  "src/trie-data.generated.ts",
  `/* Apple Huffman trie data (data/{h,spq,cpq}.data) — gzip + base64.\n` +
  ` * Only tables/embedded.ts imports this; Node reads data/*.data straight off disk\n` +
  ` * and never loads it. Generated by scripts/build-tables.mjs — do not edit. */\n${body}\n`
);
console.log(`src/trie-data.generated.ts  ${(statSync("src/trie-data.generated.ts").size / 1e6).toFixed(2)} MB`);
